### ISSUE TITLE
What is `fftSize` useful for?

### ISSUE THREAD

**Issue by LukasKalbertodt** [mathiasvr/audio-oscilloscope#4]
Hi there!

I am wondering what the `fftSize` parameter is used for. The README mentions that it is passed to the `AnalyserNode`, but what is *that* for? The visualization works completely in time domain, right? There is no frequency analysis required for the visualization as far as I can tell. Why is this `AnalyserNode` needed? 

Thanks :)

**Comment by mathiasvr** [comment]
Hello!

The fftSize determines the size of the built-in buffer, which decides how many samples (points) are used to draw the waveform. The AnalyzerNode is used to obtain these samples from the AudioContext, by calling [`AnalyserNode.getByteTimeDomainData()`](AnalyserNode.getByteTimeDomainData()).

I don't quite remember all the details, but the documentation states that the buffer used by this function is supposed to equal `fftSize` of the AnalyserNode.

Because of your question I noticed that this module actually uses a buffer size equal to `AnalyzerNode.frequencyBinCount` which is only half the fftSize. I think this might be a bug 😅 
It still works but does not take full advantage of the Analyzer.

Anyway you can try to reduce the fftSize and you should see a less detailed waveform, but in turn get better performance, as less work is needed by both this module and the AnalyzerNode.

**Comment by LukasKalbertodt** [comment]
Thanks for the quick answer! If I find some time, I might take a closer look at the source. Feel free to close this issue ^_^
